server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - name: JwtAuthFilter						
jwt:
  secret: akhilkotti12061969EurekaserverAppl!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    #Every 30 seconds, the client (e.g., api-gateway) sends a heartbeat (renewal) to Eureka Server.
    #doesn’t receive any heartbeat for 90 seconds, it assumes the service is down or unavailable, and it removes it from the Eureka
    lease-renewal-interval-in-seconds: 30		
    lease-expiration-duration-in-seconds: 90  
logging:
  level:
    '[com.netflix.discovery]': DEBUG
    '[org.springframework.cloud.gateway]': DEBUG